### ISSUE TITLE
Searching within Array of Objects

### ISSUE THREAD

**Issue by smlparry** [blackflux/object-scan#1460]
Hey there

Im trying to wrap my head around how this library works, I've got something working, but there must be a more elegant way to achieve this

Basically, my haystack looks like this (notice the surrounding brackets, this is an array of objects):

```
[
  {
    id: "1",
    pages: [
      {
        id: "2",
        pages: [
          {
            id: "3",
            pages: []
          }
        ]
      }
    ]
  }
]
```

I've got this, which is working, but _only for child nodes_ (i.e. not `id = 1`)

```
const id = "3"

objectScan(["pages.**"], {
    rtn: "value",
    abort: true,
    filterFn: ({ value }) => {
      return value ? value.id === id : false;
    },
  })(pages);
```

How could I update this to return the object:
- That has the id of `"3"`
- Is a direct child of the parent `pages` key

(Each `page` may have other attributes not outlined in the above example, which may also contain `id` keys)

Does that make sense? 

Thanks for any help, and sorry if this is the wrong place to post

**Comment by simlu** [comment]
Hello and welcome! This is absolutely the right place to ask!

This is what you want I think

```js
const objectScan = require('object-scan');

const haystack = [{ id: '1', pages: [{ id: '2', pages: [{ id: '3', pages: [] }] }] }];

const scanner = objectScan(['**(^pages$).id'], {
  rtn: 'parent',
  useArraySelector: false,
  filterFn: ({ value, context }) => value === context
});

console.log(scanner(haystack, '1'));
console.log(scanner(haystack, '3'));
```

This would also return the element if `pages` wasn't an array and just map to a single element with an `id` field.

**Comment by smlparry** [comment]
@simlu Absolute Legend!

Thanks so much for the quick response, and yep, dropped in your solution and worked perfectly! (just needed to add `abort: true` as I only want a single value returned)
![Screen Shot 2021-02-17 at 4 14 23 pm](https://user-images.githubusercontent.com/7920702/108159472-41730c00-713b-11eb-8790-e623a5c782b9.png)

Thanks again, and have a great day 😊

**Comment by simlu** [comment]
Awesome! No worries at all, always glad to help!

Closing this, but feel free to continue this conversation or open another ticket if you have any further questions
