### ISSUE TITLE
TypeError Object is not a function

### ISSUE THREAD

**Issue by alex-yobota** [blackflux/object-scan#1496]
This is definitely my fault, but I've been looking at it for an hour and I can't see the problem.

I came across object-scan from your answer to this SO question: https://stackoverflow.com/questions/33989820/recursive-way-of-removing-an-item-from-a-javascript-object

I've copied the function, more or less, and I'm trying to use it to delete some items from a tree-like object, that consists of Nodes, each of which has a `metadata` (Object) attribute, and a `children` (Array) attribute.

This is happening in React, and I've come up with this:

    class FooScreen extends Component {
    ​
      rm = (obj, val) =>
        objectScan(["++.metadata.class"], {
          abort: true,
          rtn: "bool",
          filterFn: ({ value, parents, key }) => {
            if (value === val) {
              console.log(key);
              return true;
            }
            console.log(key);
            return false;
          },
        })(obj);
    ​
      componentDidMount() {
        this.rws = new ReconnectingWebSocket(`${wsRoot}ws/foo`);
        this.rws.addEventListener("message", (message) => {
          let parsed_message = JSON.parse(message.data);
          this.rm(parsed_message, "foo");
        })
    ​
    }

Obviously the actual filter function is not correct yet, but I'm getting `TypeError: Object(...) is not a function`. I can only guess that I've screwed up the closure somehow, but I can't see how...

I'd really appreciate your help!

**Comment by simlu** [comment]
The usage of object-scan looks correct. Can you create a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) please? It's the only way to really debug this without me spending lots of time! Cheers

**Comment by alex-yobota** [comment]
Hi, thanks for the reply!

This looks like it produces more or less the same error: https://codesandbox.io/s/wonderful-sid-ee8bj?file=/src/App.js

**Comment by simlu** [comment]
@alex-yobota Looks like the import is incorrect? Should that be `import objectScan from "object-scan";`?

**Comment by alex-yobota** [comment]
@simlu Well, that's embarrassing... :facepalm:
Sorry, thank you for your help!

**Comment by alex-yobota** [comment]
If you don't mind - I'm struggling with the selector here. I'm trying to delete all nodes that have a `Class` attribute in their meta, and whose `Class` attribute matches a value:

```
{
  name: "Root",
  meta: {},
  children: [
    {
      name: "c1",
      meta: {},
      children: [
        {
          name: "c11",
          meta: {
            class: "bar"
          },
          children: []
        },
        {
          name: "c12",
          meta: {
            class: "bar"
          },
          children: []
        }
      ]
    },
    {
      name: "c2",
      meta: {},
      children: [
        {
          name: "c21",
          meta: {
            class: "bar"
          },
          children: []
        },
        {
          name: "c22",
          meta: {
            class: "bar"
          },
          children: []
        }
      ]
    }
  ]
}
```
So, I only want leaf nodes (i.e. nodes with an empty `children` array), and then I want to delete the ones whose `meta.class` matches a particular value. Is this possible?

**Comment by simlu** [comment]
Easy enough

```js
const objectScan = require('object-scan');

const data = { name: 'Root', meta: {}, children: [{ name: 'c1', meta: {}, children: [{ name: 'c11', meta: { class: 'bar' }, children: [] }, { name: 'c12', meta: { class: 'bar' }, children: [] }] }, { name: 'c2', meta: {}, children: [{ name: 'c21', meta: { class: 'bar' }, children: [] }, { name: 'c22', meta: { class: 'bar' }, children: [] }] }] };

const prune = objectScan(['**(^children$)'], {
  rtn: 'count',
  useArraySelector: false,
  filterFn: ({ parent, key, value }) => {
    if (value.children.length === 0 && value.meta.class === 'bar') {
      parent.splice(key, 1);
      return true;
    }
    return false;
  }
});

console.log(prune(data));
// => 4
console.log(JSON.stringify(data));
// => {"name":"Root","meta":{},"children":[{"name":"c1","meta":{},"children":[]},{"name":"c2","meta":{},"children":[]}]}
```

Note that this will recursively delete nodes (ie if all the children are deleted the parent might also get deleted). Is that what you want? Otherwise you'd have to use breakFn

**Comment by simlu** [comment]
So this is the version that doesn't delete then-empty parents

```js
const objectScan = require('object-scan');

const data = { name: 'Root', meta: {}, children: [{ name: 'c1', meta: {}, children: [{ name: 'c11', meta: { class: 'bar' }, children: [] }, { name: 'c12', meta: { class: 'bar' }, children: [] }] }, { name: 'c2', meta: { class: 'bar' }, children: [{ name: 'c21', meta: { class: 'bar' }, children: [] }, { name: 'c22', meta: { class: 'bar' }, children: [] }] }] };

const prune = objectScan(['**(^children$)'], {
  rtn: 'bool',
  useArraySelector: false,
  breakFn: ({ isMatch, parent, key, value }) => {
    if (isMatch && value.children.length === 0 && value.meta.class === 'bar') {
      parent.splice(key, 1);
      return true;
    }
    return false;
  }
});

console.log(prune(data));
// => true
console.log(JSON.stringify(data));
// => {"name":"Root","meta":{},"children":[{"name":"c1","meta":{},"children":[]},{"name":"c2","meta":{},"children":[]}]}
```

**Comment by alex-yobota** [comment]
I've slightly updated the data in the original issue to make it more obvious

**Comment by simlu** [comment]
@alex-yobota Did that work for you?

**Comment by alex-yobota** [comment]
That did it, thank you so much!
