### ISSUE TITLE
 json array object withing same object

### ISSUE THREAD

**Issue by supunbatagoda** [blackflux/object-scan#1638]
I can't found nested object with array object like firstObj here, to convert with secondObj. (object & array in same object)

I have an json object(firstObj) It can be nested and I have an second object containing key/value pair. I want to replace the second object's value by first one by matching value and do it's operation.

`const firstObj = {
amount_money: { amount: { mapped_field: 'payment_amt', operation: '/10' }, currency: { mapped_field: 'payment_cur', operation: null } }, source_id: { mapped_field: 'source_id', operation: null }, ship: [  { mapped_field: 'ship_country[0]', operation: null }, { mapped_field: 'ship_country[1]', operation: null } ] 
}`

`const secondObj = {
     payment_amt: 100,
     payment_cur: 'USD',
     request_id: '123ASD',
     ship_country: [        
        {
            code: 'USA',
            Title: 'America'
        },
        {
            code: 'UK',
            Title: 'England'
        }
    ]
};`

how to convert something like this,

`{
  amount_money: {
     amount: 10
     currency: 'USD'
  },
  source_id: '123ASD',
  ship: [ {America: 'USA'}, {England: 'UK'}]
}`

**Comment by simlu** [comment]
Your question has an answer here
https://stackoverflow.com/questions/67735229/find-by-key-get-value-and-replace-by-second-json-value-in-nested-json-object/67742909#67742909
