### ISSUE TITLE
What is the last commonjs release of object-scan?

### ISSUE THREAD

**Issue by webhype** [blackflux/object-scan#1763]
What is the last commonjs release of object-scan?

My project is commonjs because it needs to be packaged with vercel/pkg and that doesn't support ESM.

Thanks!

**Comment by simlu** [comment]
Interesting that `vercel/pkg` doesn't support esm ([Reference](https://github.com/vercel/pkg/issues/1291)). They are saying it's their highest priority feature request though, so hopefully they will soon!

I know `vercel/ncc` does support esm already.

Looking at the release history and considering that this project using major version numbers for breaking changes, the version you should use is [17.1.0](https://github.com/blackflux/object-scan/releases/tag/v17.1.0)!

Closing this, as unfortunately there isn't anything we can do on this side. Feel free to reply here though if you have further questions / comments!
