### ISSUE TITLE
Find object that match a specific id

### ISSUE THREAD

**Issue by cdedreuille** [blackflux/object-scan#1772]
Hi,

I found your library in [Stackoverflow](https://stackoverflow.com/questions/43636000/javascript-find-path-to-object-reference-in-nested-object) and this might be exactly what I need. I ant to use it to find the path of a deeply nested object that match a specific id. In my case, this is the code I have:

```
const findNewPath = (id: string) =>
      objectScan(["**"], {
        abort: true,
        joined: true,
        rtn: "key",
        filterFn: ({ value }) => value === id,
      })(tree);

console.log(findNewPath("WEDVuewJlH0F9uzFia9-k"));
```

This returns
```
children[0].children[0].children[0].id
```

If I want to use this path, later on, to find or set an object using lodash `_set` or `_get`, I want to remove the last item like below otherwise I'll get the id and not the containing object
```
children[0].children[0].children[0]
```

Is there a way to remove the last key in the string using objectScan? Or should I just remove it after?

**Comment by cdedreuille** [comment]
By the way, this is how I ended up writing my function in React. It works but if there's a better way I'll take it.

```
const findPath = useMemo(
    () => (id: string) => {
      const path = objectScan(["**"], {
        abort: true,
        rtn: "key",
        filterFn: ({ value }: { value: string }) => value === id,
      })(tree);
      if (path) path.pop();
      return path;
    },
    [tree]
  );
```

**Comment by simlu** [comment]
Hello and glad you're finding this library useful! Here is how you might adjust your code:

```js
const finder = objectScan(["**.id"], {
  abort: true,
  rtn: ({ key }) => key.slice(0, -1),
  filterFn: ({ value, context }) => value === context,
});
const result = finder(tree, id);
```

Note that I'm not sure how `useMemo` works, so I've excluded it here.

**Comment by cdedreuille** [comment]
Ah, I knew there was a much simpler way. Thanks a lot for your help. It works perfectly.

**Comment by simlu** [comment]
This library does a lot, and often it's not that easy to find the cleanest solution. Glad this worked for you!

FYI: Just re-read your question and, depending on your data structure, it might make sense for performance reasons to change the needle from `**.id` to `**{children[*]}.id`. This might prevent unnecessary traversal into your data structure.
