### ISSUE TITLE
Compare to jsonPath / ObjectPath

### ISSUE THREAD

**Issue by JPustkuchen** [blackflux/object-scan#963]
Great great work and really impressive!

Would be interesting to see and outline on the project page, which pro's and cons exist in comparison to for example:
- [ObjectPath](http://objectpath.org/)
- [JSONPath](https://restfulapi.net/json-jsonpath/)

For example in
- Functionality / focus
- Performance
- ...

But of course absolutely minor priority... ;)

**Comment by JPustkuchen** [comment]
Related: #164

**Comment by simlu** [comment]
Thank you for your input and I agree that this would be a good idea!

Biggest differences:
- object-scan is much more limited in functionality and hence can optimize for performance
- object-scan allows scanning for multiple keys at the same time with a single iteration

Related: https://github.com/blackflux/object-scan/issues/279

**Comment by simlu** [comment]
ObjectPath doesn't seem to support javascript. The [Readme](https://github.com/adriank/ObjectPath/blob/f5ac5bb9e0adef57be333544f66107b3727991ac/README.md) contains a note `Javascript is in beta!` (That note has been there for a while and project seems to be in maintenance mode)

**Comment by simlu** [comment]
Very rough benchmark sets object-scan about 4x the speed of jsonpath

`data.txt`
```json
{
  "store": {
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      }, {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      }, {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      }, {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
}
```

`test.js`
```js
const assert = require('assert');
const jsonPath = require('jsonpath');
const objectScan = require('./src/index');
const data = require('./data');

const bench = (name, fnRaw, count = 10000) => {
  const fn = fnRaw();
  for (let i = 0; i < count; i += 1) {
    fn();
  }
  console.time(name);
  for (let i = 0; i < count; i += 1) {
    fn();
  }
  console.timeEnd(name);
};

const jpFn = () => {
  return () => {
    const r = jsonPath.query(data, '$.store.book[*].author');
    assert(r.length === 4);
  };
};
bench('jsonpath', jpFn);

const scanFn = () => {
  const r = [];
  const scanner = objectScan(['store.book[*].author'], {
    filterFn: (key, value) => {
      r.push(value);
    }
  });
  return () => {
    r.length = 0;
    scanner(data);
    assert(r.length === 4);
  };
};
bench('object-scan', scanFn);

```

**Comment by simlu** [comment]
Here is the reason why we couldn't use jsonPath: https://stackoverflow.com/questions/55497833/jsonpath-union-of-multiple-different-paths

**Comment by simlu** [comment]
https://www.npmjs.com/package/object-path

**Comment by simlu** [comment]
Closing this as it is tracked in a different issue now.

**Comment by simlu** [comment]
object path is a different kind of library
